services:
  - type: web
    name: lims-website
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: LIMS_MODE
        value: production
